---
- hosts: localhost
  become: yes
  vars_files:
    - vars/vars.yml

  tasks:
    # Configuración de Apache
    - name: Create document root
      file:
        path: "/var/www/{{ vbDomain }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Set up Apache VirtualHost
      template:
        src: "files/wpApache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ wpVirtualHostFile }}"
      tags: [ apache ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ wpVirtualHostFile }}
      tags: [ apache ]

    #Mariadb configuration for wordpress
    - name: Creates database for WordPress
      mysql_db:
        name: "wordpress"
        state: present
        login_user: root
        login_password: "{{ mysql_root }}"
      tags: [ mysql ]

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_pass }}"
        priv: "wordpress.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root }}"
      tags: [ mysql ]

    # Configuración de WordPress
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ vbDomain }}"
        remote_src: yes
        creates: "/var/www/{{ vbDomain }}/wordpress"
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "/var/www/{{ vbDomain }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Set permissions for directories
      shell: '/usr/bin/find /var/www/{{ vbDomain }}/wordpress/ -type d -exec chmod 750 {} \;'
      tags: [ wordpress ]

    - name: Set permissions for files
      shell: '/usr/bin/find /var/www/{{ vbDomain }}/wordpress/ -type f -exec chmod 640 {} \;'
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "files/wpConfig.php.j2"
        dest: "/var/www/{{ vbDomain }}/wordpress/wp-config.php"
      tags: [ wordpress ]

    - name: Configurar permisos de /var/www/wp
      file:
        path: /var/www/web/wordpress
        state: directory
        owner: vsftpd
        group: nogroup
        mode: '0755'
        recurse: yes
    
    - name: Configurar usuario WordPress
      blockinfile:
        path: /etc/vsftpd/userconfig/{{ftp_user}}
        create: yes
        block: |
          local_root=/var/www/web/wordpress
    
    - name: Crear contraseña de usuario WordPress
      shell: >
        htpasswd -p -b /etc/vsftpd/ftpd.passwd {{ftp_user}}
        $(bcrypt-tool hash {{ ftp_pass }})
    
    # Reiniciar MySQL para aplicar cambios
    - name: Habilitar y reiniciar vsftpd
      service:
        name: vsftpd
        enabled: yes
    - name: Restart MySQL to apply changes
      service:
        name: mariadb
        state: restarted
      tags: [ mysql ]

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
      tags: [ apache ]
